#!/usr/bin/env bash
# ========================================================= #
# elib interactive setup                                    #
# ========================================================= #
# Prompts for NCBI email + optional API key, writes:
#   - ~/elibrary/config.yaml  (primary app config)
#   - ~/.config/elib/env      (shell env exports)
#   - optional line in ~/.bashrc / ~/.zshrc to source env
#
# Usage:
#   ./scripts/setup.sh
#   bash scripts/setup.sh
#   make setup
#
set -euo pipefail

ELIB_HOME="${ELIB_HOME:-$HOME/elibrary}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/elib"
ENV_FILE="$CONFIG_DIR/env"
CONFIG_FILE="$ELIB_HOME/config.yaml"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors (if TTY)
if [[ -t 1 ]]; then
  BOLD=$'\033[1m'
  DIM=$'\033[2m'
  CYAN=$'\033[36m'
  GREEN=$'\033[32m'
  YELLOW=$'\033[33m'
  RESET=$'\033[0m'
else
  BOLD=""; DIM=""; CYAN=""; GREEN=""; YELLOW=""; RESET=""
fi

info()  { printf '%s\n' "$*"; }
ok()    { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn()  { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$*"; }
header(){ printf '\n%s%s%s\n' "$BOLD$CYAN" "$*" "$RESET"; }

prompt() {
  # prompt VAR "message" [default]
  local __var="$1"
  local __msg="$2"
  local __def="${3-}"
  local __ans=""
  if [[ -n "$__def" ]]; then
    read -r -p "$__msg [$__def]: " __ans || true
    __ans="${__ans:-$__def}"
  else
    read -r -p "$__msg: " __ans || true
  fi
  printf -v "$__var" '%s' "$__ans"
}

prompt_secret() {
  local __var="$1"
  local __msg="$2"
  local __ans=""
  read -r -s -p "$__msg (leave empty to skip): " __ans || true
  echo
  printf -v "$__var" '%s' "$__ans"
}

header "elib setup"
info "Library home:  ${BOLD}$ELIB_HOME${RESET}"
info "Config file:   ${BOLD}$CONFIG_FILE${RESET}"
info "Env file:      ${BOLD}$ENV_FILE${RESET}"
info ""
info "NCBI requires a contact email for E-utilities."
info "An API key (optional) raises the rate limit from ~3 to ~10 req/s."
info "  Get a key: https://www.ncbi.nlm.nih.gov/account/settings/"
info ""

# Pre-fill from existing config / env if present
DEFAULT_EMAIL="${ELIB_NCBI_EMAIL:-${NCBI_EMAIL:-}}"
DEFAULT_KEY="${ELIB_NCBI_API_KEY:-${NCBI_API_KEY:-}}"
if [[ -z "$DEFAULT_EMAIL" && -f "$CONFIG_FILE" ]]; then
  DEFAULT_EMAIL="$(grep -E '^ncbi_email:' "$CONFIG_FILE" 2>/dev/null | sed 's/^ncbi_email:[[:space:]]*//' | tr -d '"' | tr -d "'" || true)"
fi
if [[ -z "$DEFAULT_KEY" && -f "$CONFIG_FILE" ]]; then
  DEFAULT_KEY="$(grep -E '^ncbi_api_key:' "$CONFIG_FILE" 2>/dev/null | sed 's/^ncbi_api_key:[[:space:]]*//' | tr -d '"' | tr -d "'" || true)"
  [[ "$DEFAULT_KEY" == "null" || "$DEFAULT_KEY" == "~" ]] && DEFAULT_KEY=""
fi

NCBI_EMAIL=""
NCBI_API_KEY=""
prompt NCBI_EMAIL "NCBI contact email" "${DEFAULT_EMAIL:-you@example.com}"

if [[ -z "$NCBI_EMAIL" || "$NCBI_EMAIL" == "you@example.com" || "$NCBI_EMAIL" == *"example.com" ]]; then
  warn "Using a real email is required by NCBI policy."
fi

if [[ -n "$DEFAULT_KEY" ]]; then
  prompt KEEP_KEY "Keep existing API key? (Y/n)" "Y"
  if [[ "${KEEP_KEY,,}" == "y" || "${KEEP_KEY,,}" == "yes" || -z "$KEEP_KEY" ]]; then
    NCBI_API_KEY="$DEFAULT_KEY"
    ok "Keeping existing API key"
  else
    prompt_secret NCBI_API_KEY "NCBI API key"
  fi
else
  prompt_secret NCBI_API_KEY "NCBI API key"
fi

PDF_VIEWER_DEFAULT="papers"
prompt PDF_VIEWER "PDF viewer (papers | firefox | …)" "${ELIB_PDF_VIEWER:-$PDF_VIEWER_DEFAULT}"

# Create library layout (cart, library, texts, data, exports, tmp)
header "Creating library directories"
mkdir -p "$ELIB_HOME"/{cart,texts,library,data,exports,tmp}
mkdir -p "$CONFIG_DIR"
# Repo-local scratch (gitignored) if running from a clone
mkdir -p "$REPO_ROOT/tmp"
ok "Directories ready under $ELIB_HOME (+ repo tmp/)"

# Write env file (sourced by shell)
header "Writing environment file"
umask 077
cat > "$ENV_FILE" << EOF
# elib environment — generated by scripts/setup.sh
# Source:  source $ENV_FILE
# Or add to ~/.bashrc:  [ -f $ENV_FILE ] && source $ENV_FILE

export ELIB_HOME="$ELIB_HOME"
export ELIB_CONFIG="$CONFIG_FILE"
export ELIB_NCBI_EMAIL="$NCBI_EMAIL"
export ELIB_EXPORTS_DIRECTORY="$ELIB_HOME/exports"
export ELIB_TEMP_DIRECTORY="$ELIB_HOME/tmp"
EOF

if [[ -n "$NCBI_API_KEY" ]]; then
  cat >> "$ENV_FILE" << EOF
export ELIB_NCBI_API_KEY="$NCBI_API_KEY"
export NCBI_API_KEY="$NCBI_API_KEY"
EOF
else
  cat >> "$ENV_FILE" << EOF
# export ELIB_NCBI_API_KEY=   # set later for higher NCBI rate limits
unset ELIB_NCBI_API_KEY 2>/dev/null || true
EOF
fi

if [[ -n "$PDF_VIEWER" ]]; then
  echo "export ELIB_PDF_VIEWER=\"$PDF_VIEWER\"" >> "$ENV_FILE"
fi

# Ensure ~/.local/bin on PATH for uv tool installs
cat >> "$ENV_FILE" << 'EOF'

# elib CLI (uv tool install)
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac
EOF

chmod 600 "$ENV_FILE"
ok "Wrote $ENV_FILE (mode 600)"

# Write / merge config.yaml
header "Writing $CONFIG_FILE"
# Preserve other keys if file exists
if [[ -f "$CONFIG_FILE" ]]; then
  # Use Python if available for safe merge; else rewrite core keys with sed-less approach
  if command -v python3 >/dev/null 2>&1; then
    NCBI_EMAIL="$NCBI_EMAIL" NCBI_API_KEY="$NCBI_API_KEY" PDF_VIEWER="$PDF_VIEWER" \
    ELIB_HOME="$ELIB_HOME" CONFIG_FILE="$CONFIG_FILE" python3 - <<'PY'
import os
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

path = Path(os.environ["CONFIG_FILE"])
email = os.environ.get("NCBI_EMAIL", "")
key = os.environ.get("NCBI_API_KEY") or None
viewer = os.environ.get("PDF_VIEWER") or None
home = Path(os.environ["ELIB_HOME"]).expanduser()

data = {}
if path.exists() and yaml:
    data = yaml.safe_load(path.read_text()) or {}
elif path.exists():
    # minimal parse
    for line in path.read_text().splitlines():
        if ":" in line and not line.strip().startswith("#"):
            k, _, v = line.partition(":")
            data[k.strip()] = v.strip().strip("'\"")

data["ncbi_email"] = email
if key:
    data["ncbi_api_key"] = key
elif "ncbi_api_key" in data and not key:
    # leave existing or clear
    pass
if viewer:
    data["pdf_viewer"] = viewer

# Defaults for library paths
data.setdefault("database_path", str(home / "data" / "elib.db"))
data.setdefault("target_directory", str(home / "library"))
data.setdefault("cart_directory", str(home / "cart"))
data.setdefault("texts_directory", str(home / "texts"))
data.setdefault("exports_directory", str(home / "exports"))
data.setdefault("temp_directory", str(home / "tmp"))
# Drop legacy personal bucket defaults if present
if data.get("s3_bucket") in (None, "", "bitterbeta-useast1-elibrary-landing-dev"):
    data.pop("s3_bucket", None)

if yaml:
    path.write_text(yaml.safe_dump(data, default_flow_style=False, sort_keys=False))
else:
    lines = [f"{k}: {v}" for k, v in data.items() if v is not None]
    path.write_text("\n".join(lines) + "\n")
print("merged", path)
PY
  else
    warn "python3 not found — writing a minimal config.yaml"
    cat > "$CONFIG_FILE" << EOF
ncbi_email: $NCBI_EMAIL
ncbi_api_key: ${NCBI_API_KEY:-}
database_path: $ELIB_HOME/data/elib.db
target_directory: $ELIB_HOME/library
cart_directory: $ELIB_HOME/cart
texts_directory: $ELIB_HOME/texts
exports_directory: $ELIB_HOME/exports
temp_directory: $ELIB_HOME/tmp
pdf_viewer: $PDF_VIEWER
EOF
  fi
else
  cat > "$CONFIG_FILE" << EOF
# elib config — generated by scripts/setup.sh (do not commit secrets)
ncbi_email: $NCBI_EMAIL
ncbi_api_key: ${NCBI_API_KEY:-}
database_path: $ELIB_HOME/data/elib.db
target_directory: $ELIB_HOME/library
cart_directory: $ELIB_HOME/cart
texts_directory: $ELIB_HOME/texts
exports_directory: $ELIB_HOME/exports
temp_directory: $ELIB_HOME/tmp
pdf_viewer: $PDF_VIEWER
EOF
fi
ok "Wrote $CONFIG_FILE"

# Source line for shell rc
header "Shell integration"
SOURCE_LINE="[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\"  # elib"
RC=""
if [[ -n "${BASH_VERSION-}" ]] || [[ "${SHELL-}" == *bash* ]]; then
  RC="$HOME/.bashrc"
elif [[ -n "${ZSH_VERSION-}" ]] || [[ "${SHELL-}" == *zsh* ]]; then
  RC="$HOME/.zshrc"
else
  RC="$HOME/.bashrc"
fi

prompt ADD_RC "Add source line to $RC? (Y/n)" "Y"
if [[ "${ADD_RC,,}" == "y" || "${ADD_RC,,}" == "yes" || -z "$ADD_RC" ]]; then
  if [[ -f "$RC" ]] && grep -qF "elib" "$RC" 2>/dev/null && grep -qF "$ENV_FILE" "$RC" 2>/dev/null; then
    ok "Already sourcing elib env from $RC"
  else
    {
      echo ""
      echo "# elib (NCBI email / API key / PATH)"
      echo "$SOURCE_LINE"
    } >> "$RC"
    ok "Appended to $RC"
  fi
else
  warn "Skipped shell rc. Load env with:  source $ENV_FILE"
fi

# Install CLI if uv available
header "CLI install"
if command -v uv >/dev/null 2>&1; then
  prompt INSTALL_CLI "Install/update elib CLI with uv tool? (Y/n)" "Y"
  if [[ "${INSTALL_CLI,,}" == "y" || "${INSTALL_CLI,,}" == "yes" || -z "$INSTALL_CLI" ]]; then
    (cd "$REPO_ROOT" && uv tool install --force --editable .)
    ok "elib installed to ~/.local/bin (ensure PATH includes it)"
  fi
else
  warn "uv not found — skip CLI install. Install uv, then: make install-cli"
fi

# Load env into current shell tip
header "Done"
warn "Env vars are saved to a file — they are NOT active in this shell yet."
info ""
info "Load them ${BOLD}now${RESET}:"
info "  ${BOLD}source $ENV_FILE${RESET}"
info ""
info "Or open a ${BOLD}new terminal${RESET} (setup can add a line to ~/.bashrc)."
info ""
info "Verify:"
info "  echo \$ELIB_NCBI_EMAIL"
info "  echo \${ELIB_NCBI_API_KEY:+set}    # prints 'set' if key is loaded"
info "  elib stats"
info ""
info "Process papers:"
if [[ -n "$NCBI_API_KEY" ]]; then
  info "  elib process --limit 50"
else
  info "  elib process --limit 50 --delay 0.8"
fi
info ""
ok "Setup complete."
